# Generated by Django 4.0.2 on 2022-04-04 17:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_ukoly_delete_task'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ukoly',
            name='user',
        ),
    ]
