# Generated by Django 4.0.2 on 2022-04-04 17:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('projects', '0004_remove_ukoly_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ukol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=50)),
                ('typ', models.CharField(choices=[('DŮLEŽITÉ', 'Důležité'), ('OSTATNÍ', 'ostatní')], default='OSTATNÍ', max_length=10)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='Ukoly',
        ),
    ]
