# Generated by Django 4.0.2 on 2022-04-05 06:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0010_texttest_hint'),
        ('projects', '0005_ukol_delete_ukoly'),
    ]

    operations = [
        migrations.CreateModel(
            name='Soubor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=30, null=True)),
                ('file', models.FileField(upload_to='')),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lessons.lesson')),
            ],
        ),
    ]
