# Generated by Django 4.0.2 on 2022-04-05 16:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0008_project_link'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='link',
        ),
    ]
