# Generated by Django 4.0.2 on 2022-03-13 19:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0003_rename_answers_answer_rename_exams_exam_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='exam_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='exams.exam'),
        ),
    ]
