# Generated by Django 4.0.2 on 2022-03-13 19:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0004_answer_exam_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='OpenRightAnswer',
            fields=[
                ('question', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='exams.question')),
                ('right_answer', models.TextField(max_length=200)),
            ],
        ),
    ]
