# Generated by Django 4.0.2 on 2022-03-13 19:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0005_openrightanswer'),
    ]

    operations = [
        migrations.AddField(
            model_name='openrightanswer',
            name='exam_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='exams.exam'),
        ),
    ]
