# Generated by Django 4.0.2 on 2022-03-14 09:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0006_openrightanswer_exam_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='answer',
            old_name='answer_id',
            new_name='question_id',
        ),
    ]
