# Generated by Django 4.0.2 on 2022-03-14 09:56

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('exams', '0008_examresults'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ExamResults',
            new_name='ExamResult',
        ),
        migrations.RenameModel(
            old_name='UserExamProgress',
            new_name='UserExamProgres',
        ),
    ]
