# Generated by Django 4.0.2 on 2022-03-14 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0009_rename_examresults_examresult_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='examresult',
            name='user',
        ),
        migrations.AddField(
            model_name='examresult',
            name='user_id',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
