# Generated by Django 4.0.2 on 2022-03-14 11:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0011_examresult_percentage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='examresult',
            name='percentage',
        ),
    ]
