# Generated by Django 4.0.2 on 2022-03-14 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0012_remove_examresult_percentage'),
    ]

    operations = [
        migrations.AddField(
            model_name='examresult',
            name='percentage',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
