# Generated by Django 4.0.2 on 2022-03-15 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0013_examresult_percentage'),
    ]

    operations = [
        migrations.AddField(
            model_name='examresult',
            name='take',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
