# Generated by Django 4.0.2 on 2022-03-15 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0014_examresult_take'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examresult',
            name='take',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
    ]
