# Generated by Django 4.0.2 on 2022-03-15 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0015_alter_examresult_take'),
    ]

    operations = [
        migrations.AddField(
            model_name='examresult',
            name='lock',
            field=models.TextField(blank=True, null=True),
        ),
    ]
