# Generated by Django 4.0.2 on 2022-03-15 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0016_examresult_lock'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examresult',
            name='lock',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
