# Generated by Django 4.0.2 on 2022-03-23 11:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0019_aviabletest_completetest_delete_userexamprogres'),
    ]

    operations = [
        migrations.RenameField(
            model_name='completetest',
            old_name='aviable_exam',
            new_name='complete_exam',
        ),
    ]
