# Generated by Django 4.0.2 on 2022-03-23 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0021_failedtest'),
    ]

    operations = [
        migrations.AddField(
            model_name='failedtest',
            name='take',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
    ]
