# Generated by Django 4.0.2 on 2022-03-23 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0022_failedtest_take'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='exam_number',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
