# Generated by Django 4.0.2 on 2022-04-24 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0023_exam_exam_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='question_text',
            field=models.TextField(max_length=2000),
        ),
    ]
