# Generated by Django 4.0.2 on 2022-04-24 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0024_alter_question_question_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='q_html',
            field=models.TextField(blank=True, default='', max_length=2000, null=True),
        ),
    ]
