# Generated by Django 4.0.2 on 2022-03-02 15:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Chapter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chapter_order', models.IntegerField(blank=True, null=True)),
                ('chapter_name', models.CharField(max_length=50)),
                ('chapter_link', models.CharField(default='', max_length=25)),
                ('chapter_tag', models.CharField(choices=[('READING', 'reading'), ('TEST', 'test'), ('EXERCISE', 'exercise')], default='READING', max_length=10)),
                ('allowed', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lesson_name', models.CharField(max_length=200)),
                ('lesson_group', models.CharField(default='', max_length=30)),
                ('le_short_sum', models.CharField(default='', max_length=500)),
                ('le_long_sum', models.CharField(default='', max_length=10000)),
                ('le_capitols', models.IntegerField()),
                ('le_difficulty', models.IntegerField()),
                ('le_tag', models.CharField(choices=[('LESSON', 'lekce'), ('PROJECT', 'project')], default='LESSON', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Progress',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('lesson01', models.IntegerField(default=1)),
                ('lesson02', models.IntegerField(default=0)),
                ('lesson03', models.IntegerField(default=0)),
                ('lesson04', models.IntegerField(default=0)),
                ('lesson05', models.IntegerField(default=0)),
                ('lesson06', models.IntegerField(default=0)),
                ('lesson07', models.IntegerField(default=0)),
                ('lesson08', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Requirements',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requirement', models.CharField(max_length=500)),
                ('req_lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lessons.lesson')),
            ],
        ),
        migrations.CreateModel(
            name='Goals',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goal', models.CharField(max_length=500)),
                ('goal_lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lessons.lesson')),
            ],
        ),
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_header', models.CharField(default='', max_length=50)),
                ('content_text', models.CharField(default='', max_length=500)),
                ('content_chapter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lessons.chapter')),
            ],
        ),
        migrations.AddField(
            model_name='chapter',
            name='chapter_lesson',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lessons.lesson'),
        ),
    ]
