# Generated by Django 4.0.2 on 2022-02-21 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lesson_name', models.CharField(max_length=200)),
                ('le_sum', models.CharField(max_length=500)),
                ('le_capitols', models.IntegerField()),
                ('le_difficulty', models.IntegerField()),
            ],
        ),
    ]
