# Generated by Django 4.0.2 on 2022-03-01 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='lesson_group',
            field=models.CharField(default='', max_length=30),
        ),
    ]
