# Generated by Django 4.0.2 on 2022-02-26 10:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chapter',
            old_name='chapter_tab',
            new_name='chapter_tag',
        ),
    ]
