# Generated by Django 4.0.2 on 2022-02-26 11:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lesson',
            old_name='user',
            new_name='allowed',
        ),
    ]
