# Generated by Django 4.0.2 on 2022-02-23 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0002_goals'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='le_tag',
            field=models.CharField(choices=[('LESSON', 'lesson'), ('PROJECT', 'project')], default='LESSON', max_length=10),
        ),
    ]
