# Generated by Django 4.0.2 on 2022-02-26 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0002_rename_user_lesson_allowed'),
    ]

    operations = [
        migrations.AddField(
            model_name='chapter',
            name='chapter_link',
            field=models.CharField(default='', max_length=25),
        ),
    ]
