# Generated by Django 4.0.2 on 2022-03-22 10:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0003_alter_chapter_allowed_alter_lesson_user_progress'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lesson',
            name='user_progress',
        ),
    ]
