# Generated by Django 4.0.2 on 2022-02-28 15:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0003_chapter_chapter_link'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chapter',
            old_name='users',
            new_name='allowed',
        ),
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_header', models.CharField(default='', max_length=50)),
                ('content_text', models.CharField(default='', max_length=500)),
                ('content_chapter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lessons.chapter')),
            ],
        ),
    ]
