# Generated by Django 4.0.2 on 2022-03-03 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0003_content_content_html'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='content_html',
            field=models.TextField(blank=True, default='', max_length=10000, null=True),
        ),
    ]
