# Generated by Django 4.0.2 on 2022-03-22 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0005_lesson_complete'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='lesson_order',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
