# Generated by Django 4.0.2 on 2022-03-08 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0006_lesson_le_view'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chapter',
            name='chapter_tag',
            field=models.CharField(choices=[('READING', 'reading'), ('TEXT', 'text'), ('EXAM', 'exam')], default='READING', max_length=10),
        ),
    ]
