# Generated by Django 4.0.2 on 2022-04-02 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0006_lesson_lesson_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='content_text',
            field=models.TextField(default='', max_length=1000),
        ),
    ]
