# Generated by Django 4.0.2 on 2022-04-04 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0009_texttest'),
    ]

    operations = [
        migrations.AddField(
            model_name='texttest',
            name='hint',
            field=models.TextField(blank=True, default='', max_length=100, null=True),
        ),
    ]
