# Generated by Django 4.0.2 on 2022-04-12 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0010_texttest_hint'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='content_text',
            field=models.TextField(blank=True, default='', max_length=2000, null=True),
        ),
    ]
