# Generated by Django 4.0.2 on 2022-04-13 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0011_alter_content_content_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='content_dir',
            field=models.TextField(blank=True, default='', max_length=0, null=True),
        ),
    ]
