# Generated by Django 4.0.2 on 2022-04-13 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0012_content_content_dir'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='content_dir',
            field=models.TextField(blank=True, default='', max_length=1000, null=True),
        ),
    ]
